import { Product, Category } from '@/types';

export interface MedicalProduct extends Product {
  price?: string;
  moq?: string;
  materialDetails?: string;
  availableSizes?: string;
  relatedProductSlugs?: string[];
  tradeInfo?: {
    moq?: string;
    paymentTerms?: string;
    supplyAbility?: string;
    deliveryTime?: string;
    market?: string;
    warranty?: string;
    brand?: string;
  };
  detailedSpec?: Record<string, string>;
  highlights?: string[];
  faqs?: Array<{ question: string; answer: string }>;
  regionalNotice?: string;
  modelNumber?: string;
  specifications?: Record<string, string>;
  specificationVariants?: Array<{ name: string; specs: Record<string, string> }>;
}

export const COMPANY_INFO = {
  name: 'Sri Mathurams Medical Engineering',
  legalName: 'Sri Mathurams Medical Engineering Pvt. Ltd.',
  tagline: 'Engineering Healthcare. Delivering Excellence Since 1997.',
  description: 'Premium Hospital Furniture & Medical Equipment Manufacturer trusted by hospitals, clinics, and healthcare institutions across Tamil Nadu.',
  url: 'https://srimathuramsmedical.com',
  email: 'info@srimathuramsmedical.com',
  salesEmail: 'sales@srimathuramsmedical.com',
  phone: '+91 98422 12345',
  address: {
    street: 'Plot No. 85, Industrial Estate, Peelamedu',
    city: 'Coimbatore',
    state: 'Tamil Nadu',
    postalCode: '641004',
    country: 'India',
  },
  serviceArea: 'Tamil Nadu Only',
  social: {
    linkedin: 'https://linkedin.com/company/sri-mathurams-medical',
    twitter: 'https://twitter.com/srimathuramsmed',
  },
  established: 1997,
};

export const TIMELINE_EVENTS = [
  { year: '1997', title: 'Company Established', description: 'Founded in Coimbatore to manufacture high quality hospital furniture.' },
  { year: '2005', title: 'Factory Expansion', description: 'Expanded manufacturing capacity to 10,000 sq ft state-of-the-art facility.' },
  { year: '2015', title: 'Electric ICU Beds', description: 'Launched motorized electric ICU bed production lines.' },
  { year: '2024', title: 'Tamil Nadu Trust', description: 'Serving 500+ major hospitals & healthcare centers across Tamil Nadu.' },
];

export const CATEGORIES: Category[] = [
  {
    id: 'ward-furniture',
    slug: 'ward-furniture',
    name: 'Ward Furniture',
    description: 'Bedside lockers, overbed tables, attender cots, and ward hospital beds.',
    icon: 'Bed',
  },
  {
    id: 'icu-critical-care',
    slug: 'icu-critical-care',
    name: 'ICU & Critical Care',
    description: 'Manual and motorized ICU beds with remote control and safety side rails.',
    icon: 'Activity',
  },
  {
    id: 'emergency-patient-transfer',
    slug: 'emergency-patient-transfer',
    name: 'Emergency & Patient Transfer',
    description: 'Stretcher trolleys, wheelchairs, transfer trolleys and patient shifters.',
    icon: 'Accessibility',
  },
  {
    id: 'labour-maternity',
    slug: 'labour-maternity',
    name: 'Labour & Maternity',
    description: 'Baby cradles, remote & manual labor cots, and pediatric beds.',
    icon: 'HeartPulse',
  },
  {
    id: 'examination-consultation',
    slug: 'examination-consultation',
    name: 'Examination & Consultation',
    description: 'Revolving stools, examination couches, gynec tables, and X-ray lobbies.',
    icon: 'Sparkles',
  },
  {
    id: 'medical-trolleys',
    slug: 'medical-trolleys',
    name: 'Medical Trolleys',
    description: 'Instrument trolleys, Mayo trolleys, ECG carts, crash carts, and linen trolleys.',
    icon: 'ShoppingBag',
  },
  {
    id: 'ot-equipment',
    slug: 'ot-equipment',
    name: 'OT Equipment',
    description: 'Operation theater tables, lights, anesthesia machines, foggers, and autoclaves.',
    icon: 'PlusSquare',
  },
  {
    id: 'ss-furniture-ward-accessories',
    slug: 'ss-furniture-ward-accessories',
    name: 'Stainless Steel Furniture & Ward Accessories',
    description: 'IV stands, foot steps, kick buckets, wash basins, and 3-fold screens.',
    icon: 'Armchair',
  },
  {
    id: 'accessories',
    slug: 'accessories',
    name: 'Accessories',
    description: 'Hospital mattresses, pillows, side rails, castors, actuators, and control boxes.',
    icon: 'Package',
  },
  {
    id: 'general-furniture',
    slug: 'general-furniture',
    name: 'General Furniture',
    description: 'Waiting area seater chairs, two-tier cots, and closed pharmacy trolleys.',
    icon: 'Armchair',
  },
];

export const PRODUCTS: MedicalProduct[] = [
  // --- 1. Ward Furniture ---
  {
    id: 'mf01-plain-bedside-locker',
    slug: 'plain-bedside-locker',
    modelNumber: 'MF01',
    name: 'Plain Bedside Locker',
    category: 'Ward Furniture',
    description: 'Hospital bedside locker featuring a durable single cabin layout.',
    image: '/images/Product Assets/HospitalBedsideLocker/extra-10410435.webp',
    features: ['Single Cabin Only', 'Heavy-Duty MS Sheet Construction', 'Pre-treated Powder Coated Finish'],
    specifications: {
      'Accessories': 'Removable Top Mat',
      'Castors': '50 mm Swivel Wheels',
      'Dimension': '400 × 400 × 800 mm',
      'Foldable': 'No',
      'Function': 'Bedside Patient Storage',
      'Material': 'Powder Coated MS',
      'No. of Fold': 'Single Section (No Fold)',
      'Supply Ability': '200 Per Month',
    },
    price: '3,800 INR/Unit',
    materialDetails: 'High-grade mild steel sheet pre-treated and epoxy powder coated.',
  },
  {
    id: 'mf02-deluxe-bedside-locker',
    slug: 'deluxe-bedside-locker',
    modelNumber: 'MF02',
    name: 'Deluxe Bedside Locker',
    category: 'Ward Furniture',
    description: 'Premium hospital bedside locker with top drawer and bottom storage cabin.',
    image: '/images/Product Assets/HospitalBedsideLocker/extra-10410436.webp',
    features: ['Top Smooth Slide Drawer', 'Bottom Storage Cabin', 'Stainless Steel Top Rail'],
    specifications: {
      'Accessories': 'Drawer + Cabin + Rail',
      'Castors': '50 mm Swivel Wheels',
      'Dimension': '420 × 420 × 820 mm',
      'Foldable': 'No',
      'Function': 'Bedside Patient Storage',
      'Material': 'MS with SS Accent',
      'No. of Fold': 'Single Section (No Fold)',
      'Supply Ability': '180 Per Month',
    },
    price: '4,500 INR/Unit',
    materialDetails: 'Heavy-duty steel body with smooth telescopic drawer slides.',
  },

  // --- 2. ICU & Critical Care ---
  {
    id: 'mf24-icu-cot-manual',
    slug: 'icu-cot-manual',
    modelNumber: 'MF24',
    name: 'ICU Cot Manual',
    category: 'ICU & Critical Care',
    description: 'Manual ICU hospital bed with durable ABS head/foot panels and tuck-away ABS side rails.',
    image: '/images/Product Assets/ICU CotBed/ICU-Cot.webp',
    features: ['ABS Head & Foot Arms', 'Collapsible ABS Side Rails', 'Smooth Crank Mechanism'],
    specifications: {
      'Accessories': 'IV Rod, ABS Side Rails',
      'Castors': '125 mm Central Locking',
      'Dimension': '2100 × 1000 × 600 mm',
      'Foldable': '4-Section Back & Knee',
      'Function': 'Critical ICU Care',
      'Material': 'MS Frame & ABS Panels',
      'No. of Fold': '4-Section Adjustable',
      'Supply Ability': '100 Per Month',
    },
    price: '28,500 INR/Unit',
    materialDetails: 'High-tensile MS rectangular tube frame with moulded ABS head/foot boards.',
  },
  {
    id: 'mf27-icu-cot-3-function-manual',
    slug: 'icu-cot-3-function-manual',
    modelNumber: 'MF27',
    name: 'ICU Cot 3 Function Manual',
    category: 'ICU & Critical Care',
    description: '3-function manual ICU bed featuring SS arms and SS collapsible side safety rails.',
    image: '/images/Product Assets/ICU CotBed/-Remote-ICU-Cot.webp',
    features: ['Backrest & Knee-rest Adjustments', 'Hi-Lo Height Adjustment', 'SS Collapsible Side Rails'],
    specifications: {
      'Accessories': 'SS Collapsible Side Rails',
      'Castors': '125 mm Heavy Duty Brake',
      'Dimension': '2150 × 1020 × 550 mm',
      'Foldable': '3-Function Adjustable',
      'Function': 'ICU Patient Recovery',
      'Material': 'Full Stainless Steel & MS',
      'No. of Fold': '4-Section Adjustable',
      'Supply Ability': '80 Per Month',
    },
    price: '34,000 INR/Unit',
    materialDetails: 'Heavy duty stainless steel side rails with precision screw crank systems.',
  },

  // --- 3. Emergency & Patient Transfer ---
  {
    id: 'mf38-trolley-cum-cot',
    slug: 'trolley-cum-cot',
    modelNumber: 'MF38',
    name: 'Trolley Cum Cot',
    category: 'Emergency & Patient Transfer',
    description: 'Multi-purpose patient transfer trolley cum cot equipped with SS safety side rails.',
    image: '/images/Product Assets/Beds/Hospital-Fowler-Cot-Bed.webp',
    features: ['Removable Top Stretcher', 'SS Safety Side Rails', 'IV Pole Mount Points'],
    specifications: {
      'Accessories': 'SS Rails, IV Stand',
      'Castors': '150 mm Swivel Castors',
      'Dimension': '1900 × 650 × 800 mm',
      'Foldable': 'Head Rise Section',
      'Function': 'Emergency Patient Transfer',
      'Material': 'Powder Coated MS & SS',
      'No. of Fold': '2-Section Backrest',
      'Supply Ability': '120 Per Month',
    },
    price: '18,200 INR/Unit',
    materialDetails: 'Tubular MS frame with full stainless steel side safety guards.',
  },
  {
    id: 'mf43-stretcher-trolley-ms',
    slug: 'stretcher-trolley-ms',
    modelNumber: 'MF43',
    name: 'Stretcher Trolley MS',
    category: 'Emergency & Patient Transfer',
    description: 'Heavy duty MS emergency stretcher trolley for casualty and ward transfers.',
    image: '/images/Product Assets/Stretchers/Plain-Stretcher.webp',
    features: ['Removable Stretcher Top', 'Pre-treated Epoxy Finish', 'Utility Storage Tray'],
    specifications: {
      'Accessories': 'Stretcher Canvas Top',
      'Castors': '125 mm Rubber Wheels',
      'Dimension': '1850 × 600 × 750 mm',
      'Foldable': 'No',
      'Function': 'Casualty Patient Transfer',
      'Material': 'Mild Steel Tubular Frame',
      'No. of Fold': 'Single Flat Section',
      'Supply Ability': '150 Per Month',
    },
    price: '12,500 INR/Unit',
    materialDetails: 'Epoxy powder coated mild steel construction with high density mattress top.',
  },

  // --- 4. Labour & Maternity ---
  {
    id: 'mf36-baby-cradle-ms',
    slug: 'baby-cradle-ms',
    modelNumber: 'MF36',
    name: 'Baby Cradle MS',
    category: 'Labour & Maternity',
    description: 'Sturdy hospital newborn baby cradle with clear crib container and smooth motion wheels.',
    image: '/images/Product Assets/Beds/Attender-Cot-Bed.webp',
    features: ['Clear Acrylic Baby Basin', 'Trendelenburg Tilt Position', 'Quiet Swivel Castors'],
    specifications: {
      'Accessories': 'Clear Acrylic Crib Basin',
      'Castors': '50 mm Silent Swivel',
      'Dimension': '800 × 450 × 850 mm',
      'Foldable': 'Tilt Angle Adjustable',
      'Function': 'Newborn Neonatal Care',
      'Material': 'MS Tubular & Acrylic',
      'No. of Fold': 'Single Section Tilt',
      'Supply Ability': '150 Per Month',
    },
    price: '6,800 INR/Unit',
    materialDetails: 'Ergonomic MS stand with transparent tiltable baby basket.',
  },
  {
    id: 'mf70-ss-remote-labor-cot',
    slug: 'ss-remote-labor-cot',
    modelNumber: 'MF70',
    name: 'SS Remote Labor Cot (V-Type)',
    category: 'Labour & Maternity',
    description: 'Motorized stainless steel obstetric labor delivery bed with V-type leg support.',
    image: '/images/Product Assets/Beds/Labour-Table-Hydraulic-Bed.webp',
    features: ['Motorized Remote Operation', 'V-Type Delivery Cutout', 'SS Lithotomy Crutches'],
    specifications: {
      'Accessories': 'SS Crutches, Fluid Tray',
      'Castors': '125 mm Central Lock',
      'Dimension': '1900 × 800 × 750 mm',
      'Foldable': 'Multi-Section Delivery',
      'Function': 'Obstetric Labor Delivery',
      'Material': '304 Grade Stainless Steel',
      'No. of Fold': '3-Section Motorized',
      'Supply Ability': '40 Per Month',
    },
    price: '48,000 INR/Unit',
    materialDetails: 'Full 304 grade stainless steel structure with fluid drain basin.',
  },

  // --- 5. Examination & Consultation ---
  {
    id: 'mf13-ss-revolving-stool-cushion',
    slug: 'ss-revolving-stool-cushion',
    modelNumber: 'MF13',
    name: 'SS Revolving Stool Cushion',
    category: 'Examination & Consultation',
    description: 'Height-adjustable stainless steel revolving doctor examination stool with padded seat.',
    image: '/images/Product Assets/Hospital Stool and chair/Revolving-Stool.webp',
    features: ['Cushioned Top Seat', 'Screw Thread Height Adjustment', '5-Leg Heavy Base'],
    specifications: {
      'Accessories': 'High Density Cushion Seat',
      'Castors': 'Rubber Leg Shoes / No',
      'Dimension': '350 mm Dia × 500-650 mm',
      'Foldable': 'Height Adjustable Screw',
      'Function': 'Doctor Consultation Seat',
      'Material': 'Stainless Steel & Upholstery',
      'No. of Fold': 'Single Revolving Top',
      'Supply Ability': '300 Per Month',
    },
    price: '2,200 INR/Unit',
    materialDetails: 'Stainless steel tubular legs with high density foam cushioned seat.',
  },
  {
    id: 'mf64-deluxe-examination-couch',
    slug: 'deluxe-examination-couch',
    modelNumber: 'MF64',
    name: 'Deluxe Examination Couch',
    category: 'Examination & Consultation',
    description: 'Deluxe patient examination bed featuring integrated storage cabinets.',
    image: '/images/Product Assets/Beds/Hospital-Examination-Couch-Bed.webp',
    features: ['Adjustable Headrest Section', 'Built-in Storage Cabinets', 'Padded Vinyl Top'],
    specifications: {
      'Accessories': 'Removable Foam Mattress',
      'Castors': 'Fixed Rubber Feet',
      'Dimension': '1830 × 610 × 810 mm',
      'Foldable': 'Head Rise Ratchet',
      'Function': 'Patient Examination & Scan',
      'Material': 'CRCA Steel Cabinet & Vinyl',
      'No. of Fold': '2-Section Head Adjustable',
      'Supply Ability': '90 Per Month',
    },
    price: '14,500 INR/Unit',
    materialDetails: 'CRCA steel sheet body with high-density foam leatherette mattress.',
  },

  // --- 6. Medical Trolleys ---
  {
    id: 'mf10-instrument-trolley-24x18',
    slug: 'instrument-trolley-24x18',
    modelNumber: 'MF10',
    name: 'Instrument Trolley 24 × 18',
    category: 'Medical Trolleys',
    description: 'Stainless steel two-tier surgical instrument trolley (24 x 18 inches).',
    image: '/images/Product Assets/HospitalTrolley/Theatre-Drug-Trolley.webp',
    features: ['Double Stainless Steel Shelves', 'Guard Rails on Top Shelf', 'Quiet Swivel Castors'],
    specifications: {
      'Accessories': '3-Side Railing Shelves',
      'Castors': '75 mm Silent Swivel Wheels',
      'Dimension': '610 × 450 × 800 mm',
      'Foldable': 'No',
      'Function': 'Surgical Instrument Transport',
      'Material': '304 Grade Stainless Steel',
      'No. of Fold': 'Double Shelf Rigidity',
      'Supply Ability': '250 Per Month',
    },
    price: '5,600 INR/Unit',
    materialDetails: '304 stainless steel tubular frame and polished shelves.',
  },
  {
    id: 'mf84-crash-cart-ms',
    slug: 'crash-cart-ms',
    modelNumber: 'MF84',
    name: 'Crash Cart MS',
    category: 'Medical Trolleys',
    description: 'Emergency resuscitation crash cart with color-coded modular drawers.',
    image: '/images/Product Assets/HospitalTrolley/Hospital-Crash-Cart-Trolley.webp',
    features: ['5 Modular Storage Drawers', 'IV Pole & Oxygen Cylinder Holder', 'Cardiac Board Attachment'],
    specifications: {
      'Accessories': 'IV Pole, Cardiac Board',
      'Castors': '125 mm Brake Wheels',
      'Dimension': '950 × 520 × 1000 mm',
      'Foldable': 'No',
      'Function': 'Emergency Resuscitation',
      'Material': 'Epoxy Coated MS Body',
      'No. of Fold': '5 Modular Drawers',
      'Supply Ability': '60 Per Month',
    },
    price: '26,000 INR/Unit',
    materialDetails: 'Heavy-duty steel chassis with ABS drawer compartments and central lock.',
  },

  // --- 7. OT Equipment ---
  {
    id: 'mf129-ot-table-ss',
    slug: 'ot-table-ss',
    modelNumber: 'MF129',
    name: 'OT Table SS',
    category: 'OT Equipment',
    description: 'Hydraulic surgical operation theater table crafted from 304 grade stainless steel.',
    image: '/images/Product Assets/Beds/Labour-Table-Hydraulic-Bed.webp',
    features: ['Hydraulic Height Adjustment', 'Multi-Section Radio-Translucent Top', 'SS Heavy Base'],
    specifications: {
      'Accessories': 'Arm Boards, Lithotomy Legs',
      'Castors': 'Floor Lock Mechanism',
      'Dimension': '1950 × 550 × 750-1000 mm',
      'Foldable': 'Multi-Section Positions',
      'Function': 'Surgical OT Procedures',
      'Material': '304 Grade Stainless Steel',
      'No. of Fold': '5-Section Radiotranslucent',
      'Supply Ability': '35 Per Month',
    },
    price: '78,000 INR/Unit',
    materialDetails: 'Full 304 stainless steel enclosure with radiolucent table top for C-Arm.',
  },
  {
    id: 'mf130-ot-light',
    slug: 'ot-light',
    modelNumber: 'MF130',
    name: 'OT Light Ceiling LED',
    category: 'OT Equipment',
    description: 'Shadowless LED surgical ceiling light fixture for operation theaters.',
    image: '/images/Product Assets/SurgicalSink/OT-Surgical-Scrub-Sink.webp',
    features: ['Shadowless LED Technology', 'Adjustable Color Temperature', 'Sterilizable Handle'],
    specifications: {
      'Accessories': 'Sterilizable Center Handle',
      'Castors': 'Ceiling Mount Suspension',
      'Dimension': '600 mm Dome Diameter',
      'Foldable': '360° Articulating Arm',
      'Function': 'Surgical Illumination',
      'Material': 'Aluminum Dome & LED Array',
      'No. of Fold': 'Flexible Swivel Joint',
      'Supply Ability': '50 Per Month',
    },
    price: '65,000 INR/Unit',
    materialDetails: 'High-intensity LED modules with slim aerodynamic aluminum lighthead.',
  },

  // --- 8. Stainless Steel Furniture & Ward Accessories ---
  {
    id: 'mf04-iv-stand-full-ss',
    slug: 'iv-stand-full-ss',
    modelNumber: 'MF04',
    name: 'IV Stand Full SS',
    category: 'Stainless Steel Furniture & Ward Accessories',
    description: 'Telescopic height adjustable stainless steel IV drip stand with 5-star base.',
    image: '/images/Product Assets/IVStands/-IV-Stand.webp',
    features: ['Full Stainless Steel Body', '4-Hook Drip Top', 'Heavy 5-Star Base Wheels'],
    specifications: {
      'Accessories': '4 Stainless Steel Hooks',
      'Castors': '50 mm Swivel Castors',
      'Dimension': '450 mm Base × 1350-2200 mm',
      'Foldable': 'Telescopic Lock System',
      'Function': 'IV Fluid Infusion',
      'Material': 'Full 304 Stainless Steel',
      'No. of Fold': 'Height Adjustable Pole',
      'Supply Ability': '400 Per Month',
    },
    price: '1,850 INR/Unit',
    materialDetails: '304 grade stainless steel pipe with heavy weighted anti-tip base.',
  },
  {
    id: 'mf55-double-foot-step-ms',
    slug: 'double-foot-step-ms',
    modelNumber: 'MF55',
    name: 'Double Foot Step MS',
    category: 'Stainless Steel Furniture & Ward Accessories',
    description: 'Two-step patient bed entry step stool with anti-skid rubber mats.',
    image: '/images/Product Assets/Hospital Stool and chair/Revolving-Stool.webp',
    features: ['Two Tier Step Platform', 'Non-Slip Ribbed Rubber Tops', 'Rubber Leg Shoes'],
    specifications: {
      'Accessories': 'Anti-Skid Ribbed Mats',
      'Castors': 'Rubber Leg Shoes',
      'Dimension': '450 × 450 × 400 mm',
      'Foldable': 'No',
      'Function': 'Patient Bed Access Step',
      'Material': 'Mild Steel & Ribbed Rubber',
      'No. of Fold': 'Fixed Two Tier Step',
      'Supply Ability': '350 Per Month',
    },
    price: '1,450 INR/Unit',
    materialDetails: 'Tubular MS frame pre-treated with epoxy powder coating.',
  },

  // --- 9. Accessories ---
  {
    id: 'mf102-mattress-hospital',
    slug: 'mattress-hospital',
    modelNumber: 'MF102',
    name: 'Hospital Mattress (4-Section)',
    category: 'Accessories',
    description: 'Waterproof 4-section foam mattress tailored for fowler and ICU hospital beds.',
    image: '/images/Product Assets/Beds/Plain-Examination-Bed.webp',
    features: ['4-Section Flexible Hinges', 'Waterproof Leatherette Cover', 'High Density PU Foam'],
    specifications: {
      'Accessories': 'Zipper Washable Rexine Cover',
      'Castors': 'N/A',
      'Dimension': '1980 × 900 × 100 mm',
      'Foldable': '4-Section Hinge Fold',
      'Function': 'Hospital Bed Cushioning',
      'Material': 'PU Foam & Rexine Cover',
      'No. of Fold': '4 Section Flexible',
      'Supply Ability': '300 Per Month',
    },
    price: '3,200 INR/Unit',
    materialDetails: '32-density polyurethane foam wrapped in washable zip cover.',
  },
  {
    id: 'mf137-castors-5-inches',
    slug: 'castors-5-inches',
    modelNumber: 'MF137',
    name: 'Hospital Castors 5 Inches',
    category: 'Accessories',
    description: 'Heavy duty silent polyurethane hospital bed wheels with total lock brakes.',
    image: '/images/Product Assets/Furnitures/Hospital-Foot-Stool.webp',
    features: ['5 Inch Polyurethane Wheels', 'Swivel & Total Lock Brake', 'Non-Marking Tread'],
    specifications: {
      'Accessories': 'Threaded Stem & Brake Pedal',
      'Castors': 'Swivel & Total Brake Lock',
      'Dimension': '125 mm (5 Inch) Wheel',
      'Foldable': '360° Swivel Bearing',
      'Function': 'Hospital Furniture Mobility',
      'Material': 'Polyurethane & Steel Stem',
      'No. of Fold': 'Single Swivel Unit',
      'Supply Ability': '1000 Per Month',
    },
    price: '650 INR/Unit',
    materialDetails: 'Precision ball bearing swivel castor with chrome zinc plated housing.',
  },

  // --- 10. General Furniture ---
  {
    id: 'mf104-3-seater-chair',
    slug: '3-seater-chair',
    modelNumber: 'MF104',
    name: '3 Seater Waiting Chair',
    category: 'General Furniture',
    description: 'Perforated metal 3-seater bench chair for hospital visitor waiting lobbies.',
    image: '/images/Product Assets/Furnitures/Hospital-Revolving-Stool.webp',
    features: ['Perforated Steel Back & Seat', 'Chrome Plated Armrests & Legs', 'Heavy Beam Support'],
    specifications: {
      'Accessories': 'Chrome Armrests & Legs',
      'Castors': 'Adjustable Leveling Feet',
      'Dimension': '1750 × 650 × 780 mm',
      'Foldable': 'No',
      'Function': 'Hospital Lobby Waiting',
      'Material': 'Perforated CRCA & Chrome Steel',
      'No. of Fold': 'Fixed 3-Seat Bench',
      'Supply Ability': '100 Per Month',
    },
    price: '9,500 INR/Unit',
    materialDetails: 'Cold rolled steel perforated seats with chrome plated side armrests.',
  },
  {
    id: 'mf117-two-tier-cot-ms',
    slug: 'two-tier-cot-ms',
    modelNumber: 'MF117',
    name: 'Two Tier Cot MS',
    category: 'General Furniture',
    description: 'Heavy-duty steel bunk bed cot designed for hospital attendant quarters and staff dorms.',
    image: '/images/Product Assets/Beds/Two-Tier-Cot-Bed.webp',
    features: ['Double Level Bunk Layout', 'Integrated Safety Ladder', 'Sturdy Tubular Leg Supports'],
    specifications: {
      'Accessories': 'Safety Rail & Ladder',
      'Castors': 'Rubber Leg Bush Shoes',
      'Dimension': '1980 × 900 × 1650 mm',
      'Foldable': 'No',
      'Function': 'Staff / Attendant Dormitory',
      'Material': 'Mild Steel Tubular Frame',
      'No. of Fold': 'Double Level Bunk',
      'Supply Ability': '75 Per Month',
    },
    price: '16,000 INR/Unit',
    materialDetails: 'Heavy gauge steel pipes pre-treated and powder coated in silver gray.',
  },
];
